export interface Pokemon {
  id: string;
  name: string;
  type: string;
  catchRate: number;
}

export const pokemonList: Pokemon[] = [
  { id: "0001", name: "Bulbasaur",      type: "GRASS / POISON",        catchRate: 45 },
  { id: "0002", name: "Ivysaur",        type: "GRASS / POISON",        catchRate: 45 },
  { id: "0003", name: "Venusaur",       type: "GRASS / POISON",        catchRate: 45 },
  { id: "0004", name: "Charmander",     type: "FIRE",                  catchRate: 45 },
  { id: "0005", name: "Charmeleon",     type: "FIRE",                  catchRate: 45 },
  { id: "0006", name: "Charizard",      type: "FIRE / FLYING",         catchRate: 45 },
  { id: "0007", name: "Squirtle",       type: "WATER",                 catchRate: 45 },
  { id: "0008", name: "Wartortle",      type: "WATER",                 catchRate: 45 },
  { id: "0009", name: "Blastoise",      type: "WATER",                 catchRate: 45 },
  { id: "0010", name: "Caterpie",       type: "BUG",                   catchRate: 255 },
  { id: "0011", name: "Metapod",        type: "BUG",                   catchRate: 120 },
  { id: "0012", name: "Butterfree",     type: "BUG / FLYING",          catchRate: 45 },
  { id: "0013", name: "Weedle",         type: "BUG / POISON",          catchRate: 255 },
  { id: "0014", name: "Kakuna",         type: "BUG / POISON",          catchRate: 120 },
  { id: "0015", name: "Beedrill",       type: "BUG / POISON",          catchRate: 45 },
  { id: "0016", name: "Pidgey",         type: "NORMAL / FLYING",       catchRate: 255 },
  { id: "0017", name: "Pidgeotto",      type: "NORMAL / FLYING",       catchRate: 120 },
  { id: "0018", name: "Pidgeot",        type: "NORMAL / FLYING",       catchRate: 45 },
  { id: "0019", name: "Rattata",        type: "NORMAL",                catchRate: 255 },
  { id: "0020", name: "Raticate",       type: "NORMAL",                catchRate: 127 },
  { id: "0021", name: "Spearow",        type: "NORMAL / FLYING",       catchRate: 255 },
  { id: "0022", name: "Fearow",         type: "NORMAL / FLYING",       catchRate: 90 },
  { id: "0023", name: "Ekans",          type: "POISON",                catchRate: 255 },
  { id: "0024", name: "Arbok",          type: "POISON",                catchRate: 90 },
  { id: "0025", name: "Pikachu",        type: "ELECTRIC",              catchRate: 190 },
  { id: "0026", name: "Raichu",         type: "ELECTRIC",              catchRate: 75 },
  { id: "0027", name: "Sandshrew",      type: "GROUND",                catchRate: 255 },
  { id: "0028", name: "Sandslash",      type: "GROUND",                catchRate: 90 },
  { id: "0029", name: "Nidoran F",      type: "POISON",                catchRate: 235 },
  { id: "0030", name: "Nidorina",       type: "POISON",                catchRate: 120 },
  { id: "0031", name: "Nidoqueen",      type: "POISON / GROUND",       catchRate: 45 },
  { id: "0032", name: "Nidoran M",      type: "POISON",                catchRate: 235 },
  { id: "0033", name: "Nidorino",       type: "POISON",                catchRate: 120 },
  { id: "0034", name: "Nidoking",       type: "POISON / GROUND",       catchRate: 45 },
  { id: "0035", name: "Clefairy",       type: "NORMAL",                catchRate: 150 },
  { id: "0036", name: "Clefable",       type: "NORMAL",                catchRate: 25 },
  { id: "0037", name: "Vulpix",         type: "FIRE",                  catchRate: 190 },
  { id: "0038", name: "Ninetales",      type: "FIRE",                  catchRate: 75 },
  { id: "0039", name: "Jigglypuff",     type: "NORMAL",                catchRate: 170 },
  { id: "0040", name: "Wigglytuff",     type: "NORMAL",                catchRate: 50 },
  { id: "0041", name: "Zubat",          type: "POISON / FLYING",       catchRate: 255 },
  { id: "0042", name: "Golbat",         type: "POISON / FLYING",       catchRate: 90 },
  { id: "0043", name: "Oddish",         type: "GRASS / POISON",        catchRate: 255 },
  { id: "0044", name: "Gloom",          type: "GRASS / POISON",        catchRate: 120 },
  { id: "0045", name: "Vileplume",      type: "GRASS / POISON",        catchRate: 45 },
  { id: "0046", name: "Paras",          type: "BUG / GRASS",           catchRate: 190 },
  { id: "0047", name: "Parasect",       type: "BUG / GRASS",           catchRate: 75 },
  { id: "0048", name: "Venonat",        type: "BUG / POISON",          catchRate: 190 },
  { id: "0049", name: "Venomoth",       type: "BUG / POISON",          catchRate: 75 },
  { id: "0050", name: "Diglett",        type: "GROUND",                catchRate: 255 },
  { id: "0051", name: "Dugtrio",        type: "GROUND",                catchRate: 50 },
  { id: "0052", name: "Meowth",         type: "NORMAL",                catchRate: 255 },
  { id: "0053", name: "Persian",        type: "NORMAL",                catchRate: 90 },
  { id: "0054", name: "Psyduck",        type: "WATER",                 catchRate: 190 },
  { id: "0055", name: "Golduck",        type: "WATER",                 catchRate: 75 },
  { id: "0056", name: "Mankey",         type: "FIGHTING",              catchRate: 190 },
  { id: "0057", name: "Primeape",       type: "FIGHTING",              catchRate: 75 },
  { id: "0058", name: "Growlithe",      type: "FIRE",                  catchRate: 190 },
  { id: "0059", name: "Arcanine",       type: "FIRE",                  catchRate: 75 },
  { id: "0060", name: "Poliwag",        type: "WATER",                 catchRate: 255 },
  { id: "0061", name: "Poliwhirl",      type: "WATER",                 catchRate: 120 },
  { id: "0062", name: "Poliwrath",      type: "WATER / FIGHTING",      catchRate: 45 },
  { id: "0063", name: "Abra",           type: "PSYCHIC",               catchRate: 200 },
  { id: "0064", name: "Kadabra",        type: "PSYCHIC",               catchRate: 100 },
  { id: "0065", name: "Alakazam",       type: "PSYCHIC",               catchRate: 50 },
  { id: "0066", name: "Machop",         type: "FIGHTING",              catchRate: 180 },
  { id: "0067", name: "Machoke",        type: "FIGHTING",              catchRate: 90 },
  { id: "0068", name: "Machamp",        type: "FIGHTING",              catchRate: 45 },
  { id: "0069", name: "Bellsprout",     type: "GRASS / POISON",        catchRate: 255 },
  { id: "0070", name: "Weepinbell",     type: "GRASS / POISON",        catchRate: 120 },
  { id: "0071", name: "Victreebel",     type: "GRASS / POISON",        catchRate: 45 },
  { id: "0072", name: "Tentacool",      type: "WATER / POISON",        catchRate: 190 },
  { id: "0073", name: "Tentacruel",     type: "WATER / POISON",        catchRate: 60 },
  { id: "0074", name: "Geodude",        type: "ROCK / GROUND",         catchRate: 255 },
  { id: "0075", name: "Graveler",       type: "ROCK / GROUND",         catchRate: 120 },
  { id: "0076", name: "Golem",          type: "ROCK / GROUND",         catchRate: 45 },
  { id: "0077", name: "Ponyta",         type: "FIRE",                  catchRate: 190 },
  { id: "0078", name: "Rapidash",       type: "FIRE",                  catchRate: 60 },
  { id: "0079", name: "Slowpoke",       type: "WATER / PSYCHIC",       catchRate: 190 },
  { id: "0080", name: "Slowbro",        type: "WATER / PSYCHIC",       catchRate: 75 },
  { id: "0081", name: "Magnemite",      type: "ELECTRIC / STEEL",      catchRate: 190 },
  { id: "0082", name: "Magneton",       type: "ELECTRIC / STEEL",      catchRate: 60 },
  { id: "0083", name: "Farfetch'd",     type: "NORMAL / FLYING",       catchRate: 45 },
  { id: "0084", name: "Doduo",          type: "NORMAL / FLYING",       catchRate: 190 },
  { id: "0085", name: "Dodrio",         type: "NORMAL / FLYING",       catchRate: 45 },
  { id: "0086", name: "Seel",           type: "WATER",                 catchRate: 190 },
  { id: "0087", name: "Dewgong",        type: "WATER / ICE",           catchRate: 75 },
  { id: "0088", name: "Grimer",         type: "POISON",                catchRate: 190 },
  { id: "0089", name: "Muk",            type: "POISON",                catchRate: 75 },
  { id: "0090", name: "Shellder",       type: "WATER",                 catchRate: 190 },
  { id: "0091", name: "Cloyster",       type: "WATER / ICE",           catchRate: 60 },
  { id: "0092", name: "Gastly",         type: "GHOST / POISON",        catchRate: 190 },
  { id: "0093", name: "Haunter",        type: "GHOST / POISON",        catchRate: 90 },
  { id: "0094", name: "Gengar",         type: "GHOST / POISON",        catchRate: 45 },
  { id: "0095", name: "Onix",           type: "ROCK / GROUND",         catchRate: 45 },
  { id: "0096", name: "Drowzee",        type: "PSYCHIC",               catchRate: 190 },
  { id: "0097", name: "Hypno",          type: "PSYCHIC",               catchRate: 75 },
  { id: "0098", name: "Krabby",         type: "WATER",                 catchRate: 225 },
  { id: "0099", name: "Kingler",        type: "WATER",                 catchRate: 60 },
  { id: "0100", name: "Voltorb",        type: "ELECTRIC",              catchRate: 190 },
  { id: "0101", name: "Electrode",      type: "ELECTRIC",              catchRate: 60 },
  { id: "0102", name: "Exeggcute",      type: "GRASS / PSYCHIC",       catchRate: 90 },
  { id: "0103", name: "Exeggutor",      type: "GRASS / PSYCHIC",       catchRate: 45 },
  { id: "0104", name: "Cubone",         type: "GROUND",                catchRate: 190 },
  { id: "0105", name: "Marowak",        type: "GROUND",                catchRate: 75 },
  { id: "0106", name: "Hitmonlee",      type: "FIGHTING",              catchRate: 45 },
  { id: "0107", name: "Hitmonchan",     type: "FIGHTING",              catchRate: 45 },
  { id: "0108", name: "Lickitung",      type: "NORMAL",                catchRate: 45 },
  { id: "0109", name: "Koffing",        type: "POISON",                catchRate: 190 },
  { id: "0110", name: "Weezing",        type: "POISON",                catchRate: 60 },
  { id: "0111", name: "Rhyhorn",        type: "GROUND / ROCK",         catchRate: 120 },
  { id: "0112", name: "Rhydon",         type: "GROUND / ROCK",         catchRate: 45 },
  { id: "0113", name: "Chansey",        type: "NORMAL",                catchRate: 30 },
  { id: "0114", name: "Tangela",        type: "GRASS",                 catchRate: 45 },
  { id: "0115", name: "Kangaskhan",     type: "NORMAL",                catchRate: 45 },
  { id: "0116", name: "Horsea",         type: "WATER",                 catchRate: 225 },
  { id: "0117", name: "Seadra",         type: "WATER",                 catchRate: 75 },
  { id: "0118", name: "Goldeen",        type: "WATER",                 catchRate: 225 },
  { id: "0119", name: "Seaking",        type: "WATER",                 catchRate: 60 },
  { id: "0120", name: "Staryu",         type: "WATER",                 catchRate: 225 },
  { id: "0121", name: "Starmie",        type: "WATER / PSYCHIC",       catchRate: 60 },
  { id: "0122", name: "Mr. Mime",       type: "PSYCHIC",               catchRate: 45 },
  { id: "0123", name: "Scyther",        type: "BUG / FLYING",          catchRate: 45 },
  { id: "0124", name: "Jynx",           type: "ICE / PSYCHIC",         catchRate: 45 },
  { id: "0125", name: "Electabuzz",     type: "ELECTRIC",              catchRate: 45 },
  { id: "0126", name: "Magmar",         type: "FIRE",                  catchRate: 45 },
  { id: "0127", name: "Pinsir",         type: "BUG",                   catchRate: 45 },
  { id: "0128", name: "Tauros",         type: "NORMAL",                catchRate: 45 },
  { id: "0129", name: "Magikarp",       type: "WATER",                 catchRate: 255 },
  { id: "0130", name: "Gyarados",       type: "WATER / FLYING",        catchRate: 45 },
  { id: "0131", name: "Lapras",         type: "WATER / ICE",           catchRate: 45 },
  { id: "0132", name: "Ditto",          type: "NORMAL",                catchRate: 35 },
  { id: "0133", name: "Eevee",          type: "NORMAL",                catchRate: 45 },
  { id: "0134", name: "Vaporeon",       type: "WATER",                 catchRate: 45 },
  { id: "0135", name: "Jolteon",        type: "ELECTRIC",              catchRate: 45 },
  { id: "0136", name: "Flareon",        type: "FIRE",                  catchRate: 45 },
  { id: "0137", name: "Porygon",        type: "NORMAL",                catchRate: 45 },
  { id: "0138", name: "Omanyte",        type: "ROCK / WATER",          catchRate: 45 },
  { id: "0139", name: "Omastar",        type: "ROCK / WATER",          catchRate: 45 },
  { id: "0140", name: "Kabuto",         type: "ROCK / WATER",          catchRate: 45 },
  { id: "0141", name: "Kabutops",       type: "ROCK / WATER",          catchRate: 45 },
  { id: "0142", name: "Aerodactyl",     type: "ROCK / FLYING",         catchRate: 45 },
  { id: "0143", name: "Snorlax",        type: "NORMAL",                catchRate: 25 },
  { id: "0144", name: "Articuno",       type: "ICE / FLYING",          catchRate: 3  },
  { id: "0145", name: "Zapdos",         type: "ELECTRIC / FLYING",     catchRate: 3  },
  { id: "0146", name: "Moltres",        type: "FIRE / FLYING",         catchRate: 3  },
  { id: "0147", name: "Dratini",        type: "DRAGON",                catchRate: 45 },
  { id: "0148", name: "Dragonair",      type: "DRAGON",                catchRate: 45 },
  { id: "0149", name: "Dragonite",      type: "DRAGON / FLYING",       catchRate: 45 },
  { id: "0150", name: "Mewtwo",         type: "PSYCHIC",               catchRate: 3  },
  { id: "0151", name: "Mew",            type: "PSYCHIC",               catchRate: 45 }
];
